Remove invalid rows from test data tsv files
These were causing errors of the form

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 888: ordinal not in range(128)

These errors occur on HEAD of hgvs repo as well on Python 3.6. Decided to remove the commented data rather than try to figure out a workaround. TSV should have columnar data IMO and not include these long comment blocks.